import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
<body>
  <script
    fcm_service_path="/firebase-messaging-sw.js"
    src="https://sdk.resul.io/handlers/edbd3c99fe37452db5a3cd04dbdcbb70.sdk"
    defer
  ></script>

  {children}
</body>

    </html>
  );
}
